# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sesa236189\OneDrive - Schneider Electric\Documents\Perso\pop-it\Projects\Zuora\ZTool_clean\ZTool_clean\BillingPreview\UI\qt\ZTools.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(523, 397)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(517, 0))
        self.centralwidget.setStyleSheet("background:black;")
        self.centralwidget.setObjectName("centralwidget")
        self.frameHeader = QtWidgets.QFrame(self.centralwidget)
        self.frameHeader.setGeometry(QtCore.QRect(6, 6, 898, 185))
        self.frameHeader.setStyleSheet("background:white;")
        self.frameHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHeader.setObjectName("frameHeader")
        self.formLayout = QtWidgets.QFormLayout(self.frameHeader)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleLabel = QtWidgets.QLabel(self.frameHeader)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolIconLabel = QtWidgets.QLabel(self.frameHeader)
        self.toolIconLabel.setText("")
        self.toolIconLabel.setPixmap(QtGui.QPixmap(":/Buttons/Image1.png"))
        self.toolIconLabel.setObjectName("toolIconLabel")
        self.horizontalLayout.addWidget(self.toolIconLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.descriptionLabel = QtWidgets.QLabel(self.frameHeader)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.horizontalLayout_2.addWidget(self.descriptionLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.toolButton = QtWidgets.QToolButton(self.frameHeader)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Buttons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.startButton = QtWidgets.QCommandLinkButton(self.frameHeader)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.startButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Buttons/bigGo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon1)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_3.addWidget(self.startButton)
        self.allInOneCheckBox = QtWidgets.QCheckBox(self.frameHeader)
        self.allInOneCheckBox.setObjectName("allInOneCheckBox")
        self.horizontalLayout_3.addWidget(self.allInOneCheckBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loginButton = QtWidgets.QCommandLinkButton(self.frameHeader)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.loginButton.setFont(font)
        self.loginButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Buttons/login_username.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton.setIcon(icon2)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout_4.addWidget(self.loginButton)
        self.billingButton = QtWidgets.QCommandLinkButton(self.frameHeader)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.billingButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Buttons/billng.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.billingButton.setIcon(icon3)
        self.billingButton.setObjectName("billingButton")
        self.horizontalLayout_4.addWidget(self.billingButton)
        self.extendButton = QtWidgets.QCommandLinkButton(self.frameHeader)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.extendButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Buttons/extend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extendButton.setIcon(icon4)
        self.extendButton.setObjectName("extendButton")
        self.horizontalLayout_4.addWidget(self.extendButton)
        self.arrangeButton = QtWidgets.QCommandLinkButton(self.frameHeader)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.arrangeButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Buttons/arrange.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrangeButton.setIcon(icon5)
        self.arrangeButton.setObjectName("arrangeButton")
        self.horizontalLayout_4.addWidget(self.arrangeButton)
        self.finalizeButton = QtWidgets.QCommandLinkButton(self.frameHeader)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.finalizeButton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Buttons/finalize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.finalizeButton.setIcon(icon6)
        self.finalizeButton.setObjectName("finalizeButton")
        self.horizontalLayout_4.addWidget(self.finalizeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.frameWizard = QtWidgets.QFrame(self.centralwidget)
        self.frameWizard.setGeometry(QtCore.QRect(10, 200, 461, 80))
        self.frameWizard.setStyleSheet("background:white;")
        self.frameWizard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameWizard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameWizard.setObjectName("frameWizard")
        self.wizardStackedWidget = QtWidgets.QStackedWidget(self.frameWizard)
        self.wizardStackedWidget.setGeometry(QtCore.QRect(10, 10, 441, 61))
        self.wizardStackedWidget.setObjectName("wizardStackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.label_5 = QtWidgets.QLabel(self.loginPage)
        self.label_5.setGeometry(QtCore.QRect(50, 20, 35, 10))
        self.label_5.setObjectName("label_5")
        self.wizardStackedWidget.addWidget(self.loginPage)
        self.billingPage = QtWidgets.QWidget()
        self.billingPage.setObjectName("billingPage")
        self.label_4 = QtWidgets.QLabel(self.billingPage)
        self.label_4.setGeometry(QtCore.QRect(50, 30, 35, 10))
        self.label_4.setObjectName("label_4")
        self.wizardStackedWidget.addWidget(self.billingPage)
        self.frameResult = QtWidgets.QFrame(self.centralwidget)
        self.frameResult.setGeometry(QtCore.QRect(10, 280, 461, 80))
        self.frameResult.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameResult.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameResult.setObjectName("frameResult")
        self.scrollArea = QtWidgets.QScrollArea(self.frameResult)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 441, 61))
        self.scrollArea.setStyleSheet("background:white")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 439, 59))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 523, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.wizardStackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZTools by Stef !"))
        self.titleLabel.setText(_translate("MainWindow", "bDO - Billing forecasting"))
        self.descriptionLabel.setText(_translate("MainWindow", "Generate Billing Preview Run from Zuora and lookup the result with subscription data source"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.startButton.setText(_translate("MainWindow", "Start New Process !"))
        self.allInOneCheckBox.setText(_translate("MainWindow", "All In One Step"))
        self.loginButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Login to your Zuora tenant</p></body></html>"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.billingButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Launch your Billing Preview and import the temporary file</p></body></html>"))
        self.billingButton.setText(_translate("MainWindow", "Billing"))
        self.extendButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Launch Subscription details export and integrate results to billing preview</p></body></html>"))
        self.extendButton.setText(_translate("MainWindow", "Extend info"))
        self.arrangeButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Arrange headers and choose which one to export</p></body></html>"))
        self.arrangeButton.setText(_translate("MainWindow", "Arrange"))
        self.finalizeButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Generate final file (xls, csv, html,...)</p></body></html>"))
        self.finalizeButton.setText(_translate("MainWindow", "Finalize"))
        self.label_5.setText(_translate("MainWindow", "Page 1"))
        self.label_4.setText(_translate("MainWindow", "Page 2"))

import ztools_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

